--Create New Table
CREATE TABLE [dbo].[Cust](
	[CustId] int identity(1,1),
	[CustNum] [varchar](20) NOT NULL,
	[cbank_ref] [char](14) NULL Default(''),
	[CustName] [varchar](200) NULL,
	[BilStAdd] [varchar](200) NULL,
	[BilCtAdd] [varchar](64) NULL,
	[BillTel] [varchar](30) NULL,
	[BillTel2] [varchar](50) NULL,
	[Fax] [varchar](50) NULL,
	[SvcStAdd] [varchar](200) NULL,
	[SvcCtAdd] [varchar](64) NULL,
	[SvcTelNo] [varchar](20) NULL,
	[Status] [varchar](1) NULL,
	[RateId] int NOT NULL,
	[ZoneId] int NOT NULL,
	[BillNum] [int] NULL,
	[DueDate] Date NULL,
	[DueDate2] Date NULL,
	[LastPayDate] Date NULL,
	[DiscStatus] [varchar](1) NULL,
	[DiscDate] Date NULL,
	[PnoteNo] [varchar](12) NULL,
	[PnoteAmt] [money] NULL,
	[PnoteDate] Date NULL,
	[CStat] [int] NULL,
	[Abandoned] [int] NULL  Default(0),
	[ApplORNum] [varchar](20) NULL,
	[ORDeposit] [money] NULL,
	[ORDate] Date NULL,
	[lpn] [bit] NOT NULL Default(0),
	[legalstat] [bit] NOT NULL Default(0),
	[legalcode] [int] NOT NULL Default(0),
	[cdeveloperid] [char](10) NULL Default(''),
	[ccelnumber] [char](12) NULL Default(''),
	[cemailaddr] [varchar](200) NULL Default(''),
	[etext] [bit] NOT NULL Default(0),
	[remarks] [varchar](50) NULL,
	[Applnum] [varchar](25) NULL,
	[BuyerClassID] [int] NULL,
	[Age] int NULL,
	[Sex] [varchar](20) NULL,
	[Civil_Status] [varchar](20) NULL,
	[Birthday] Date NULL,
	[zip_code] [varchar](8) NULL,
	[type_application] [char](1) NULL,
	[company_name] [varchar](30) NULL,
	[authorized_rep] [varchar](30) NULL,
	[designation] [varchar](30) NULL,
	[Nature_bus] [varchar](30) NULL,
	[Year_bus] [numeric](9, 0) NULL,
	[Fox_no] [varchar](15) NULL,
	[Sec_reg_no] [varchar](15) NULL,
	[Picturepath] [varchar](250) NULL,
	[dappldate] Date NULL,
	[oldcustnum] [varchar](20) NULL,
	[lmetercharge] [bit] NULL,
	[dmetercharge] [datetime] NULL,
	[PenaltyStat] [varchar](1) NULL DEFAULT(0),
	[PenaltyAmt] [money] NULL,
	[SeniorDate] Date NULL,
	[SeniorID] [varchar](20) NULL,
	[ServAppl] [varchar](60) NULL,
	[UserName] [varchar](50) NULL,
	[Dttransaction] [datetime] NULL,
	[polypoint1] [varchar](50) NULL,
	[polypoint2] [varchar](50) NULL,
	[polypoint3] [varchar](50) NULL,
	[polypoint4] [varchar](50) NULL,
	[singlepoint1] [varchar](50) NULL,
	[singlepoint2] [varchar](50) NULL,
	[pan] [bigint] NULL,
	[brgyid] [int] NULL,
	[iswriteoff] Bit NULL,
	[Block] [varchar](50) NULL,
	[Lot] [varchar](50) NULL,
	[CTC] [varchar](20) NULL,
	[municipality_id] [int] NULL,
	[sap_status] [int] NULL,
	[sap_date] Date NULL,
	[septage_status] [int] NOT NULL DEFAULT(0),
	[septage_location] [int] NULL,
	[septage_applied] [datetime] NULL,
	[septage_duration] [int] NULL,
	[septage_duration_type] [int] NULL,
	[septage_schedule_last] Date NULL,
	[septage_info_extra] [int] NULL,
	[nprint_Contract] [int] NULL,
	[HOACustId] int NULL,
	 CONSTRAINT [PK_Cust] PRIMARY KEY CLUSTERED 
	(
		[CustId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	,
	FOREIGN KEY ([RateId]) REFERENCES Rates([RateId]),
	FOREIGN KEY ([ZoneId]) REFERENCES Zones([ZoneId])
) ON [PRIMARY]