CREATE TABLE [dbo].[forSyncAccount](
	[id] [int] IDENTITY(1,1) NOT NULL,
	CustId int,
	[dateinserted] [datetime] NULL,
	[info] [varchar](10) NULL,
 CONSTRAINT [PK_forSyncAccount] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

