CREATE NONCLUSTERED INDEX ix_Rates_I ON [dbo].[Rates]
(
	[RateId] ASC
)
INCLUDE ( 	[RateName],
	[rgroupid]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]