--Recreate Cpaym
CREATE TABLE Cpaym
(
	[PymntNum] [int] identity(1,1) NOT NULL,
	[OldPymntNum] [int] NULL,
	[CustId] int NOT NULL,
	[RbillNum] [varchar](20) NULL,
	[PymntMode] [int] NOT NULL,
	[PymntTyp] int NOT NULL,
	[PymntStat] int NOT NULL,
	[PayAmnt] [money] NOT NULL,
	[Penalty] [money] NULL DEFAULT(0),
	[Subtot1] [money] NOT NULL DEFAULT(0),
	[Subtot2] [money] NOT NULL DEFAULT(0),
	[Subtot3] [money] NOT NULL DEFAULT(0),
	[Subtot4] [money] NOT NULL DEFAULT(0),
	[Subtot5] [money] NOT NULL DEFAULT(0),
	[Subtot6] [money] NOT NULL DEFAULT(0),
	[Subtot7] [money] NOT NULL DEFAULT(0),
	[Subtot8] [money] NOT NULL DEFAULT(0),
	[PayDate] Date NOT NULL,
	[PymntDtl] [varchar](120) NULL,
	[ORNum] [varchar](20) NULL,
	[RcvdBy] [varchar](100) NULL DEFAULT(0),
	[subtot9] [money] NOT NULL DEFAULT(0),
	[oldorno] [varchar](20) NULL,
	[ntype] [numeric](1, 0) NULL,
	[capproved] [char](10) NULL DEFAULT(''),
	[Subtot10] [money] NULL DEFAULT(0),
	[tax1] [money] NULL DEFAULT(0),
	[tax2] [money] NULL DEFAULT(0),
	[Subtot11] [money] NOT NULL DEFAULT(0),
	[Subtot12] [money] NOT NULL DEFAULT(0),
	[rpymntnum] [int] NULL,
	[Subtot13] [money] NOT NULL DEFAULT(0),
	[Subtot14] [money] NOT NULL DEFAULT(0),
	[pnno] [varchar](20) NULL DEFAULT(''),
	[pn_amount] [money] NOT NULL DEFAULT(0),
	[rrecfee] [money] NOT NULL DEFAULT(0),
	[rwaterm] [money] NOT NULL DEFAULT(0),
	[rpenfee] [money] NOT NULL DEFAULT(0),
	[rservdep] [money] NOT NULL DEFAULT(0),
	[rprocfee] [money] NOT NULL DEFAULT(0),
	[rinsfee] [money] NOT NULL DEFAULT(0),
	[rtechfee] [money] NOT NULL DEFAULT(0),
	[rwatfee] [money] NOT NULL DEFAULT(0),
	[PaymentCenter_Transaction_id] [int] NULL DEFAULT(0),
	[wdorletter] [varchar](20) NULL DEFAULT(''),
	[isLateCancelled] [bit] NULL,
	CreatedDate Datetime NULL,
	 CONSTRAINT [PK_Cpaym] PRIMARY KEY NONCLUSTERED 
	(
		[PymntNum] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	,
	FOREIGN KEY ([CustId]) REFERENCES Cust([CustId])
	) ON [PRIMARY]