--Create New Table
CREATE TABLE [dbo].[customersInformations]
(
	[customerID] int identity(1,1),
	[custNum] [varchar](20) NOT NULL,
	[atmRef] [varchar](10) NULL Default(''),
	[customerName] [varchar](200) NULL,
	[billingStreetAdd] [varchar](200) NULL,
	[billingCityAdd] [varchar](64) NULL,
	[billingTelNo1] [varchar](30) NULL,
	[billingTelNo2] [varchar](50) NULL,
	[FAXaddress] [varchar](50) NULL,
	[svcStreetAdd] [varchar](200) NULL,
	[svcCityAdd] [varchar](64) NULL,
	[svcTelNo] [varchar](20) NULL,
	[customerStatusID] [varchar](1) NULL,
	[classID] int NOT NULL,
	[zoneID] int NOT NULL,
	[lastPayDate] Date NULL,
	[abanDoned] [int] NULL  Default(0),
	[developerID] [char](10) NULL Default(''),
	[mobileNumber] [char](12) NULL Default(''),
	[emailAddr] [varchar](200) NULL Default(''),
	[applNum] [varchar](25) NULL,
	[buyerClassID] [int] NULL,
	[Sex] [varchar](20) NULL,
	[civilStatus] [varchar](20) NULL,
	[birthDay] Date NULL,
	[picturePath] [varchar](250) NULL,
	[oldCustNum] [varchar](20) NULL,
	[penaltyStat] [varchar](1) NULL DEFAULT(0),
	[seniorDate] Date NULL,
	[seniorID] [varchar](20) NULL,
	[userName] [varchar](50) NULL,
	[entryDate] [datetime] NULL,
	[polypoint1] [varchar](50) NULL,
	[polypoint2] [varchar](50) NULL,
	[polypoint3] [varchar](50) NULL,
	[polypoint4] [varchar](50) NULL,
	[singlepoint1] [varchar](50) NULL,
	[singlepoint2] [varchar](50) NULL,
	[PAN] [bigint] NULL,
	[brgyID] [int] NULL,
	[isWriteOff] Bit NULL,
	[Block] [varchar](50) NULL,
	[Lot] [varchar](50) NULL,
	[CTC] [varchar](20) NULL,
	[municipalityID] [int] NULL,
	[sapStatus] [int] NULL,
	[sapDate] Date NULL,
	[septage_status] [int] NOT NULL DEFAULT(0),
	[septage_location] [int] NULL,
	[septage_applied] [datetime] NULL,
	[septage_duration] [int] NULL,
	[septage_duration_type] [int] NULL,
	[septage_schedule_last] Date NULL,
	[septage_info_extra] [int] NULL,
	[nprint_Contract] [int] NULL,
	[HOAcustomerID] int NULL,
	 CONSTRAINT [PK_Cust] PRIMARY KEY CLUSTERED 
	(
		[customerID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	,
	FOREIGN KEY ([classID]) REFERENCES claSSifications([classID]),
	FOREIGN KEY ([zoneID]) REFERENCES ZoneS([zoneID])
)
ON [PRIMARY];